# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab8ee6f170941223c5d7015ee892338cbaaa42fa13b684a1d91bc0dec5dac66f271ba68054fd962610f6b56aed692ae6085f77656ad3ad4bf6deb3b1877ce00a

test:
  secret_key_base: 96564dffcbe505219ab1f221e1bc88f7028e03bef4a220edb88c83f07c7ba7936652fbb9ead87430af9a8e494145da8b65949ec45e34b05d6205f6fbace61c71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
